// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Start/res
// hash: 34fb53714d9b8912
// </auto-generated>

import { defineAssets } from '../../../yzforge/runtime';

export const assets = defineAssets({
    views: {
    },
    parts: {
    },
    runtime: {
    },
});
