// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Start/res
// hash: a5789e6b38f4cacf
// </auto-generated>

import { defineAssets } from 'yzforge';

export const assets = defineAssets({
    views: {
    },
    parts: {
    },
    runtime: {
    },
});
