// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Start/res/content/config
// hash: 416729ab6151c9e2
// </auto-generated>

import { defineConfig, tableRef } from '../../../yzforge/runtime';

export const config = defineConfig({
    tables: {
        startItems: tableRef({ name: 'res/content/config/StartItems', primaryKey: 'id' }),
    },
});
