// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Start/res/content/config
// hash: 22e069cf752e0d6e
// </auto-generated>

import { defineConfig, tableRef } from 'yzforge';

export const config = defineConfig({
    tables: {
        startItems: tableRef({ name: 'res/content/config/StartItems', primaryKey: 'id' }),
    },
});
