// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/content-packs/Start
// hash: 2c8c5acd00e9c4eb
// </auto-generated>

import { defineContentPack, contentPackConfigRef } from '../../../yzforge/runtime';

export const StartTest2ContentPack = defineContentPack({
    id: 'start.test2',
    owner: 'Start',
    name: 'Test2',
    bundle: 'yzforge-content-pack-start-test2',
    libraries: [],
    refs: {
        testWaves: contentPackConfigRef('res/content/config/TestWaves', { primaryKey: 'id' }),
    },
});

export const contentPacks = {
    Test2: StartTest2ContentPack,
};
