// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Start/module.json
// hash: 66976e57f9095233
// </auto-generated>

import { defineModuleEntry, registerModuleEntry } from '../../../yzforge/runtime';
import { StartModule } from './StartModule';
import { assets } from './assets.generated';
import { config } from './config.generated';
registerModuleEntry(defineModuleEntry({
    name: 'Start',
    bundle: 'yzforge-module-start',
    type: StartModule,
    assets,
    config,
    libraries: [],
}));
