// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/app/bootstrap
// hash: f1503dd68474e363
// </auto-generated>

import type { App } from 'yzforge';

export async function installGeneratedExtensions(_app: App): Promise<void> {}
