// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/app/bootstrap
// hash: 22528d18a2622fbb
// </auto-generated>

import type { App } from '../../yzforge/runtime';

export async function installGeneratedExtensions(_app: App): Promise<void> {}
