// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/res
// hash: 2dce3146d5ab9f8a
// </auto-generated>

import { defineAssets } from '../../../yzforge/runtime';

export const assets = defineAssets({
    views: {
    },
    parts: {
    },
    runtime: {
    },
});
