// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/res
// hash: 51137fda08e087b9
// </auto-generated>

import { defineAssets } from 'yzforge';

export const assets = defineAssets({
    views: {
    },
    parts: {
    },
    runtime: {
    },
});
