// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/res/content/config
// hash: 25ba394949a43b67
// </auto-generated>

import { defineConfig, tableRef } from 'yzforge';

export const config = defineConfig({
    tables: {
    },
});
