// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/res/content/config
// hash: 6eb43e085e05494c
// </auto-generated>

import { defineConfig, tableRef } from '../../../yzforge/runtime';

export const config = defineConfig({
    tables: {
    },
});
