// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/library.json
// hash: e633ab92480ca831
// </auto-generated>

import { defineLibraryEntry, registerLibraryEntry } from '../../../yzforge/runtime';
import { assets } from './assets.generated';
import { config } from './config.generated';
import { providers } from './providers';
registerLibraryEntry(defineLibraryEntry({
    name: 'Test',
    bundle: 'yzforge-lib-test',
    assets,
    config,
    libraries: [],
    tokens: providers,
}));
