// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/library.json
// hash: c5aea0ad2611684b
// </auto-generated>

import { defineLibraryRef } from 'yzforge';
export const TestRef = defineLibraryRef({
    name: 'Test',
    bundle: 'yzforge-lib-test',
    libraries: [],
});
