// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/library.json
// hash: eeabe37dff9df03e
// </auto-generated>

import { YZFORGE_RUNTIME_ABI } from 'yzforge';
import { defineLibraryRef } from 'yzforge/authoring';
export const TestRef = defineLibraryRef({
    abi: YZFORGE_RUNTIME_ABI,
    name: 'Test',
    bundle: 'yzforge-lib-test',
    libraries: [],
});
