// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/library.json
// hash: 3a519513fcbc8f5e
// </auto-generated>

import { defineLibraryRef } from '../../../yzforge/runtime';
export const TestRef = defineLibraryRef({
    name: 'Test',
    bundle: 'yzforge-lib-test',
    libraries: [],
});
