// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Home/res
// hash: d5065eeb052c57e3
// </auto-generated>

import { defineAssets } from '../../../yzforge/runtime';

export const assets = defineAssets({
    views: {},
    parts: {},
    runtime: {},
});
