// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Home/res
// hash: 0bdf1df9b257ef28
// </auto-generated>

import { defineAssets } from '../../../yzforge/runtime';

export const assets = defineAssets({
    views: {
    },
    parts: {
    },
    runtime: {
    },
});
