// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Home/res/content/config
// hash: b797f1b0ad929be5
// </auto-generated>

import { defineConfig } from '../../../yzforge/runtime';

export const config = defineConfig({
    tables: {},
});
