// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Home/module.json
// hash: 3de614a8c7767294
// </auto-generated>

import { defineModuleEntry, registerModuleEntry } from '../../../yzforge/runtime';
import { HomeModule } from './HomeModule';
import { assets } from './assets.generated';
import { config } from './config.generated';
registerModuleEntry(defineModuleEntry({
    name: 'Home',
    bundle: 'yzforge-module-home',
    type: HomeModule,
    assets,
    config,
    libraries: [],
}));
