'use strict';

const fs = require('fs');
const path = require('path');
const { toPosix, verifyGeneratedJsonHash, walk } = require('./fs-utils');

const SCAN_ROOTS = [
  'assets/app',
  'assets/modules',
  'assets/libraries',
  'assets/content-packs',
];

function relativePath(projectRoot, filePath) {
  return toPosix(path.relative(projectRoot, filePath));
}

function isInsideProject(projectRoot, filePath) {
  const root = path.resolve(projectRoot);
  const target = path.resolve(filePath);
  return target === root || target.startsWith(`${root}${path.sep}`);
}

function isGeneratedTs(filePath) {
  if (!filePath.endsWith('.ts')) {
    return false;
  }
  if (!fs.existsSync(filePath)) {
    return false;
  }
  const content = fs.readFileSync(filePath, 'utf8');
  return content.includes('// <auto-generated>')
    && content.includes('// generator: yzforge@0.1.0')
    && content.includes('// </auto-generated>');
}

function isGeneratedJson(projectRoot, filePath) {
  const rel = relativePath(projectRoot, filePath);
  if (!/^assets\/content-packs\/[^/]+\/[^/]+\/manifest\.generated\.json$/.test(rel)) {
    return false;
  }
  if (!fs.existsSync(filePath)) {
    return false;
  }
  try {
    const result = verifyGeneratedJsonHash(JSON.parse(fs.readFileSync(filePath, 'utf8')));
    return result.ok;
  } catch (_error) {
    return false;
  }
}

function isCleanableGeneratedFile(projectRoot, filePath, options = {}) {
  if (options.includeScripts === false && isGeneratedTs(filePath)) {
    return false;
  }
  return isGeneratedTs(filePath) || isGeneratedJson(projectRoot, filePath);
}

function collectGeneratedFiles(projectRoot, options = {}) {
  const files = [];
  for (const scanRoot of SCAN_ROOTS) {
    const root = path.join(projectRoot, scanRoot);
    for (const filePath of walk(root, (candidate) => isCleanableGeneratedFile(projectRoot, candidate, options))) {
      if (!isInsideProject(projectRoot, filePath)) {
        continue;
      }
      files.push(relativePath(projectRoot, filePath));
    }
  }
  return Array.from(new Set(files)).sort((a, b) => a.localeCompare(b));
}

function cleanGenerated(projectRoot, options = {}) {
  const files = collectGeneratedFiles(projectRoot, options);
  const removed = [];
  const failed = [];

  if (options.dryRun) {
    return {
      ok: true,
      dryRun: true,
      count: files.length,
      removed: [],
      files,
      failed,
    };
  }

  for (const rel of files) {
    const filePath = path.join(projectRoot, rel);
    if (!isInsideProject(projectRoot, filePath)) {
      failed.push({ path: rel, reason: 'path is outside project root' });
      continue;
    }
    if (!isCleanableGeneratedFile(projectRoot, filePath, options)) {
      failed.push({ path: rel, reason: 'file is no longer a YZForge generated file' });
      continue;
    }
    try {
      fs.unlinkSync(filePath);
      removed.push(rel);
    } catch (error) {
      failed.push({ path: rel, reason: error.message });
    }
  }

  return {
    ok: failed.length === 0,
    dryRun: false,
    count: removed.length,
    removed,
    files,
    failed,
  };
}

module.exports = {
  cleanGenerated,
  collectGeneratedFiles,
  isCleanableGeneratedFile,
};
