'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { FRAMEWORK_VERSION } = require('./version');

function toPosix(value) {
  return String(value || '').replace(/\\/g, '/');
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function stripJsonComments(content) {
  return content
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/.*$/gm, '$1');
}

function readJsonc(filePath) {
  return JSON.parse(stripJsonComments(fs.readFileSync(filePath, 'utf8')));
}

function writeTextIfChanged(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  if (!isTextChanged(filePath, content)) {
    return false;
  }
  const next = content.endsWith('\n') ? content : `${content}\n`;
  fs.writeFileSync(filePath, next, 'utf8');
  return true;
}

function isTextChanged(filePath, content) {
  const next = content.endsWith('\n') ? content : `${content}\n`;
  if (fs.existsSync(filePath)) {
    const current = fs.readFileSync(filePath, 'utf8');
    if (current === next || normalizeLineEndings(current) === normalizeLineEndings(next)) {
      return false;
    }
  }
  return true;
}

function writeJsonIfChanged(filePath, value) {
  return writeTextIfChanged(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function hashContent(source, body) {
  return crypto.createHash('sha256').update(`${toPosix(source)}\n${normalizeLineEndings(body)}`).digest('hex').slice(0, 16);
}

function normalizeLineEndings(value) {
  return String(value || '').replace(/\r\n?/g, '\n');
}

function generatedText(source, body) {
  const normalizedBody = normalizeLineEndings(body).trim();
  const hash = hashContent(source, normalizedBody);
  return [
    '// <auto-generated>',
    `// generator: yzforge@${FRAMEWORK_VERSION}`,
    `// source: ${toPosix(source)}`,
    `// hash: ${hash}`,
    '// </auto-generated>',
    '',
    normalizedBody,
    '',
  ].join('\n');
}

function verifyGeneratedHash(content) {
  const sourceMatch = content.match(/^\/\/ source: (.+)$/m);
  const hashMatch = content.match(/^\/\/ hash: ([a-f0-9]+)$/m);
  const end = content.indexOf('// </auto-generated>');
  if (!sourceMatch || !hashMatch || end < 0) {
    return { ok: false, reason: 'missing generated header' };
  }
  const body = normalizeLineEndings(content.slice(end + '// </auto-generated>'.length)).trim();
  const expected = hashContent(sourceMatch[1], body);
  return {
    ok: expected === hashMatch[1],
    expected,
    actual: hashMatch[1],
  };
}

function generatedJson(source, value) {
  const body = normalizeLineEndings(JSON.stringify(value, null, 2));
  return {
    ...value,
    _generated: {
      generator: `yzforge@${FRAMEWORK_VERSION}`,
      source: toPosix(source),
      hash: hashContent(source, body),
    },
  };
}

function verifyGeneratedJsonHash(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return { ok: false, reason: 'invalid generated JSON' };
  }
  const meta = value._generated;
  if (!meta || typeof meta !== 'object' || !meta.source || !meta.hash) {
    return { ok: false, reason: 'missing generated metadata' };
  }
  const body = { ...value };
  delete body._generated;
  const expected = hashContent(meta.source, normalizeLineEndings(JSON.stringify(body, null, 2)));
  return {
    ok: expected === meta.hash,
    expected,
    actual: meta.hash,
  };
}

function kebabCase(name) {
  return String(name)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

function isPascalCase(name) {
  return /^[A-Z][A-Za-z0-9]*$/.test(String(name || ''));
}

function walk(root, predicate, results = []) {
  if (!fs.existsSync(root)) {
    return results;
  }
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      walk(fullPath, predicate, results);
    } else if (!predicate || predicate(fullPath)) {
      results.push(fullPath);
    }
  }
  return results;
}

module.exports = {
  generatedText,
  generatedJson,
  isTextChanged,
  isPascalCase,
  kebabCase,
  readJson,
  readJsonc,
  stripJsonComments,
  toPosix,
  verifyGeneratedHash,
  verifyGeneratedJsonHash,
  walk,
  writeJsonIfChanged,
  writeTextIfChanged,
};
