'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

function toPosix(value) {
  return String(value || '').replace(/\\/g, '/');
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function stripJsonComments(content) {
  return content
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/.*$/gm, '$1');
}

function readJsonc(filePath) {
  return JSON.parse(stripJsonComments(fs.readFileSync(filePath, 'utf8')));
}

function writeTextIfChanged(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const next = content.endsWith('\n') ? content : `${content}\n`;
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf8') === next) {
    return false;
  }
  fs.writeFileSync(filePath, next, 'utf8');
  return true;
}

function writeJsonIfChanged(filePath, value) {
  return writeTextIfChanged(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function hashContent(source, body) {
  return crypto.createHash('sha256').update(`${source}\n${body}`).digest('hex').slice(0, 16);
}

function generatedText(source, body) {
  const hash = hashContent(source, body);
  return [
    '// <auto-generated>',
    '// generator: yzforge@0.1.0',
    `// source: ${toPosix(source)}`,
    `// hash: ${hash}`,
    '// </auto-generated>',
    '',
    body.trim(),
    '',
  ].join('\n');
}

function verifyGeneratedHash(content) {
  const sourceMatch = content.match(/^\/\/ source: (.+)$/m);
  const hashMatch = content.match(/^\/\/ hash: ([a-f0-9]+)$/m);
  const end = content.indexOf('// </auto-generated>');
  if (!sourceMatch || !hashMatch || end < 0) {
    return { ok: false, reason: 'missing generated header' };
  }
  const body = content.slice(end + '// </auto-generated>'.length).trim();
  const expected = hashContent(sourceMatch[1], body);
  return {
    ok: expected === hashMatch[1],
    expected,
    actual: hashMatch[1],
  };
}

function kebabCase(name) {
  return String(name)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}

function isPascalCase(name) {
  return /^[A-Z][A-Za-z0-9]*$/.test(String(name || ''));
}

function walk(root, predicate, results = []) {
  if (!fs.existsSync(root)) {
    return results;
  }
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      walk(fullPath, predicate, results);
    } else if (!predicate || predicate(fullPath)) {
      results.push(fullPath);
    }
  }
  return results;
}

module.exports = {
  generatedText,
  isPascalCase,
  kebabCase,
  readJson,
  readJsonc,
  stripJsonComments,
  toPosix,
  verifyGeneratedHash,
  walk,
  writeJsonIfChanged,
  writeTextIfChanged,
};
