// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Home/module.json
// hash: eab208e750363d62
// </auto-generated>

export interface HomeEnterParams {
    readonly from?: string;
}
