// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Start/module.json
// hash: 3afa04aef36519fc
// </auto-generated>

export interface StartEnterParams {
    readonly from?: string;
}
