// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Home/module.json
// hash: f599dd737203f340
// </auto-generated>

import { defineModuleRef } from '../../../yzforge/runtime';
import type { HomeEnterParams } from '../../contracts/modules/Home.contract.generated';

export const HomeRef = defineModuleRef<HomeEnterParams>({
    name: 'Home',
    bundle: 'yzforge-module-home',
    libraries: [],
});
