// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Start/module.json
// hash: 13e6e9af0b99d9cd
// </auto-generated>

import { defineModuleRef } from '../../../yzforge/runtime';
import type { StartEnterParams } from '../../contracts/modules/Start.contract.generated';

export const StartRef = defineModuleRef<StartEnterParams>({
    name: 'Start',
    bundle: 'yzforge-module-start',
    libraries: [],
});
