// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Start/module.json
// hash: c62646742ab28483
// </auto-generated>

import { defineModuleRef } from 'yzforge';
import type { StartEnterParams } from '../../contracts/modules/Start.contract.generated';

export const StartRef = defineModuleRef<StartEnterParams>({
    name: 'Start',
    bundle: 'yzforge-module-start',
    libraries: [],
});
