// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/modules/Start/module.json
// hash: fdbdc1404a095bea
// </auto-generated>

import { YZFORGE_RUNTIME_ABI } from 'yzforge';
import { defineModuleRef } from 'yzforge/authoring';
import type { StartEnterParams } from '../../contracts/modules/Start.contract.generated';

export const StartRef = defineModuleRef<StartEnterParams>({
    abi: YZFORGE_RUNTIME_ABI,
    name: 'Start',
    bundle: 'yzforge-module-start',
    libraries: [],
});
