// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/library.json
// hash: f01d0f4670749cb5
// </auto-generated>

import { defineLibraryTokens } from '../../../yzforge/runtime';

export interface TestTokenMap {}

export const TestTokens = defineLibraryTokens<TestTokenMap>('Test', {
});
