// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/libraries/Test/library.json
// hash: dece17af1a147b63
// </auto-generated>

import { defineLibraryTokens } from 'yzforge';

export interface TestTokenMap {}

export const TestTokens = defineLibraryTokens<TestTokenMap>('Test', {
});
