// <auto-generated>
// generator: yzforge@0.1.0
// source: assets/app/registry
// hash: 744ef6471e00f151
// </auto-generated>

export { StartRef } from './modules/Start.ref.generated';
export { TestRef } from './libraries/Test.ref.generated';
